spring:
  application:
    name: docintel

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

cloud:
  storage:
    provider: aws
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket:
        name: ${AWS_S3_BUCKET}
      endpoint: ${AWS_S3_ENDPOINT}